services:
  # API Gateway
  api-gateway:
    image: gchugo/api-gateway:latest
    ports:
      - "5001:5001"  # Mapeo correcto del puerto
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=myuser        
      - RABBITMQ_PASSWORD=mypassword
    networks:
      - app-network

  # Consumer
  consumer:
    container_name: consumer
    image: gchugo/consumer:latest
    ports:
      - "5002:5002"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=myuser       
      - RABBITMQ_PASSWORD=mypassword 
    depends_on:
      - rabbitmq  # Asegurarse de que RabbitMQ esté disponible antes de iniciar el consumer
    volumes:
      - consumer_data:/app/data  # Monta el volumen para los datos CSV
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser        
      RABBITMQ_DEFAULT_PASS: mypassword    
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - app-network

  # Otros servicios como electricidad, ocupación, seguridad, temperatura
  electricidad:
    image: gchugo/sensor-electricidad:latest
    deploy:
      replicas: 7
    depends_on:
      - api-gateway
    networks:
      - app-network

  ocupacion:
    image: gchugo/sensor-ocupacion:latest
    deploy:
      replicas: 6
    depends_on:
      - api-gateway
    networks:
      - app-network

  seguridad:
    image: gchugo/sensor-seguridad:latest
    deploy:
      replicas: 3
    depends_on:
      - api-gateway
    networks:
      - app-network

  temperatura:
    image: gchugo/sensor-temperatura:latest
    deploy:
      replicas: 4
    depends_on:
      - api-gateway
    networks:
      - app-network

volumes:
  consumer_data:

networks:
  app-network:
    driver: bridge